fio = input("Введите ФИО исследователя ")
data = input("Введите дату ")
name_exp = input("Введите название эксперимента ")
conclusion = input("Введите вывод ")
with open("journal.txt", "w", encoding="utf-8") as report:
    report.write("+--------------------------------------------------+\n")
    report.write("| Электронный лабораторный журнал                  |\n")
    report.write("+--------------------------------------------------+\n")
    report.write(f"|ФИО исследователя    :\t{fio}                      |\n")
    report.write(f"|Дата                 :\t{data}                        |\n")
    report.write(f"|Эксперимент          :\t{name_exp}                         |\n")
    report.write("+--------------------------------------------------+\n")
    report.write(f"|Вывод:\t\n       {conclusion}                    |\n")
    report.write("+--------------------------------------------------+")
